### ISSUE TITLE
Step2: port direction of enable and ready in module 2

### ISSUE THREAD

**Issue by csuwalaka** [dyumnin/NCG_Interview#1]
Port direction of enable and ready in module 2 is not clear. If I assume module 1 and 2 as two different interfaces to same DDR PHY IP then will enable and ready in module 2 have same port direction as module 1 (enable(input),ready(output))?

**Comment by jahagirdar** [comment]
That's correct, The enable,Ready protocol can have the same direction in all implementation.

**Comment by csuwalaka** [comment]
Thanks. The concept is clear now.
